site_name: SyncGames

theme:
  name: material
nav:
  - User story: index.md
  - Descrizione del progetto: description.md
  - Comprensione del problema: problem.md
  - Pubblico e target: target.md
  - Criticità: crit.md
  - Requisiti necessari: req.md